name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write

    steps:
      - name: Profile metrics (core dashboard)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN || github.token }}
          user: SaadK123
          config_timezone: Canada/Montreal

          template: classic
          base: header, activity, community

          plugin_languages: yes
          plugin_habits: yes
          plugin_habits_facts: no
          plugin_habits_charts: yes

          plugin_isocalendar: yes
          plugin_stargazers: yes
          plugin_lines: yes
          plugin_licenses: yes
          plugin_topics: yes
          plugin_stars: yes

          plugin_repositories: yes
          plugin_followup: yes
          plugin_people: yes
          plugin_reactions: yes
          plugin_achievements: yes
          plugin_notable: yes
          plugin_discussions: yes
          plugin_projects: yes
          plugin_gists: yes
          plugin_contributors: yes
          plugin_calendar: yes
          plugin_introduction: yes

          filename: metrics.svg
          output_action: commit
          committer_message: "chore: update metrics"

      - name: Repository metrics (repo template)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN || github.token }}
          user: SaadK123
          repo: SaadK123
          template: repository
          filename: metrics.repository.svg
          output_action: commit
          committer_message: "cho_
